

export const AUTH_LOGIN = "AUTH_LOGIN"
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCESS"
export const AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE"

export const AUTH_REGISTER = "AUTH_REGISTER"
export const AUTH_REGISTER_SUCCESS = "AUTH_REGISTER_SUCCESS"
export const AUTH_REGISTER_FAILURE = "AUTH_REGISTER_FAILURE"

export const AUTH_GET_STATUS = "AUTH_GET_STATUS"
export const AUTH_GET_STATUS_SUCCESS = "AUTH_GET_STATUS_SUCCESS"
export const AUTH_GET_STATUS_FAILURE = "AUTH_GET_STATUS_FAILURE"

export const GET_INFO = "GET_INFO"
export const GET_INFO_SUCCESS = "GET_INFO_SUCCESS"
export const GET_INFO_FAILURE = "GET_INFO_FAILURE"

export const GET_POST = "GET_POST"
export const GET_POST_SUCCESS = "GET_POST_SUCCESS"
export const GET_POST_FAILURE = "GET_POST_FAILURE"

export const GET_NPOST_SUCCESS = "GET_NPOST_SUCCESS"

export const POST_QUESTION = "POST_QUESTION"
export const POST_QUESTION_SUCCESS = "POST_QUESTION_SUCCESS"
export const POST_QUESTION_FAILURE = "POST_QUESTION_FAILURE"

export const POST_ANSWER = "POST_ANSWER"
export const POST_ANSWER_SUCCESS = "POST_ANSWER_SUCCESS"
export const POST_ANSWER_FAILURE = "POST_ANSWER_FAILURE"

export const POST_REMOVE = "POST_REMOVE"
export const POST_REMOVE_SUCCESS = "POST_REMOVE_SUCCESS"
export const POST_REMOVE_FAILURE = "POST_REMOVE_FAILURE"

export const GET_RANDOM_ACCOUNT = "GET_RANDOM_ACCOUNT"
export const GET_RANDOM_ACCOUNT_SUCCESS = "GET_RANDOM_ACCOUNT_SUCCESS"
export const GET_RANDOM_ACCOUNT_FAILURE = "GET_RANDOM_ACCOUNT_FAILURE"

export const ADMIN_GET = "ADMIN_GET"
export const ADMIN_GET_SUCCESS = "ADMIN_GET_SUCCESS"
export const ADMIN_GET_FAILURE = "ADMIN_GET_FAILURE"